//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Data.Entity.Core.Objects.DataClasses;

namespace Entidades
{
    using System;
    using System.Collections.Generic;

    public partial class Contacto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Contacto()
        {
            this.Telefonos = new HashSet<Telefono>();
        }

        public int IdContacto { get; set; }
        public string Nombre { get; set; }
        public string Email { get; set; }
        public Nullable<int> IdGrupo { get; set; }


        public virtual Grupos Grupos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Telefono> Telefonos { get; set; }

        public Contacto(string nombre, string email, int? idGrupo, Grupos grupos, ICollection<Telefono> telefonos)
        {
            Nombre = nombre;
            Email = email;
            IdGrupo = idGrupo;
            Grupos = grupos;
            Telefonos = telefonos;
        }

        public string devuelveTelefonosEnString(ICollection<Telefono> telefonos)
        {
            String stringDeTelefonos = "";
            if (telefonos != null)
            {
                foreach (Telefono telefono in telefonos)
                {
                    stringDeTelefonos = stringDeTelefonos + telefono.ToString();
                }
            }

            return stringDeTelefonos;
        }

        public override string ToString()
        {
            return Nombre;
        }

    }


}
