//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Telefono : IEquatable<Telefono>
    {
        public Telefono()
        {

        }

        public Telefono(string numero, string descripcion)
        {
            Numero = numero;
            Descripcion = descripcion;
        }

        public Telefono(int idContacto, string numero, string descripcion, Contacto contacto)
        {
            IdContacto = idContacto;
            Numero = numero;
            Descripcion = descripcion;
            Contacto = contacto;
        }

        public int IdContacto { get; set; }
        public string Numero { get; set; }
        public string Descripcion { get; set; }
    
        public virtual Contacto Contacto { get; set; }

        public override bool Equals(object obj)
        {
            return Equals(obj as Telefono);
        }

        public bool Equals(Telefono other)
        {
            return !(other is null) &&
                   Numero == other.Numero;
        }

        public override int GetHashCode()
        {
            return -1449941195 + EqualityComparer<string>.Default.GetHashCode(Numero);
        }

        public override string ToString()
        {
            return Numero.ToString();
        }

        public static bool operator ==(Telefono left, Telefono right)
        {
            return EqualityComparer<Telefono>.Default.Equals(left, right);
        }

        public static bool operator !=(Telefono left, Telefono right)
        {
            return !(left == right);
        }
    }
}
